/*
 * TikHub Private API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tikhub

// GetNoteInfoV5Request GetNoteInfoV5Request
type GetNoteInfoV5Request struct {
	// Note Id，笔记ID/Note ID
	NoteId string `json:"note_id,omitempty" xml:"note_id"`
	// Xsec Token，X-Sec-Token，可以从搜索接口中获取/X-Sec-Token, can be obtained from the search interface
	XsecToken string `json:"xsec_token,omitempty" xml:"xsec_token"`
	// Cookie，用户自行提供的已登录的网页Cookie/User provided logged-in web Cookie
	Cookie string `json:"cookie,omitempty" xml:"cookie"`
	// Proxy，代理，格式：http://用户名:密码@IP:端口/Proxy, format: http://username:password@IP:port
	Proxy string `json:"proxy,omitempty" xml:"proxy"`
}
