/*
 * TikHub Private API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tikhub

// HttpValidationError HTTPValidationError
type HttpValidationError struct {
	// Detail
	Detail []ValidationError `json:"detail,omitempty" xml:"detail"`
}
