/*
 * TikHub Private API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tikhub

// TikTokAppV3ContentTranslate TikTok_APP_V3_Content_Translate
type TikTokAppV3ContentTranslate struct {
	// Trg Lang，目标语言ISO639-1代码，例如：zh-Hans/ Target language ISO639-1 code, e.g. zh-Hans
	TrgLang string `json:"trg_lang,omitempty" xml:"trg_lang"`
	// Src Content，源语言内容，也就是需要翻译的内容/ Source language content, i.e. the content to be translated
	SrcContent string `json:"src_content,omitempty" xml:"src_content"`
}
