/*
 * TikHub Private API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tikhub

// BodyAmazonCaptchaApiV1CaptchaAmazonCaptchaPost Body_amazon_captcha_api_v1_captcha_amazon_captcha_post
type BodyAmazonCaptchaApiV1CaptchaAmazonCaptchaPost struct {
	// App Id，App ID
	AppId string `json:"app_id" xml:"app_id"`
	// Url，URL
	Url string `json:"url" xml:"url"`
	// Proxy，Proxy
	Proxy map[string]interface{} `json:"proxy,omitempty" xml:"proxy"`
}
