/*
 * TikHub Private API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tikhub

// XBogusModel XBogusModel
type XBogusModel struct {
	// Url，请求的API URL，不需要进行编码 | The requested API URL, no need to encode
	Url string `json:"url" xml:"url"`
	// User Agent，请求API时的User-Agent | User-Agent when requesting the API
	UserAgent string `json:"user_agent" xml:"user_agent"`
}
