/*
 * TikHub Private API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tikhub

// BodyFetchHotAccountListApiV1DouyinBillboardFetchHotAccountListPost Body_fetch_hot_account_list_api_v1_douyin_billboard_fetch_hot_account_list_post
type BodyFetchHotAccountListApiV1DouyinBillboardFetchHotAccountListPost struct {
	// Date Window，时间窗口，格式 小时，默认24小时
	DateWindow string `json:"date_window,omitempty" xml:"date_window"`
	// Page Num，页码，默认1
	PageNum string `json:"page_num,omitempty" xml:"page_num"`
	// Page Size，每页数量，默认10
	PageSize string `json:"page_size,omitempty" xml:"page_size"`
	// Query Tag，子级垂类标签，空则为全部，多个标签需传入{\"value\": \"{顶级垂类标签id}\", \"children\": [{\"value\": \"{子级垂类标签id}\"}, {\"value\": \"{子级垂类标签id}\"}]}
	QueryTag map[string]interface{} `json:"query_tag,omitempty" xml:"query_tag"`
}
