/*
 * TikHub Private API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tikhub

// BodyRecaptchaV3ApiV1CaptchaRecaptchaV3Post Body_recaptcha_v3_api_v1_captcha_recaptcha_v3_post
type BodyRecaptchaV3ApiV1CaptchaRecaptchaV3Post struct {
	// Sitekey，Sitekey
	Sitekey string `json:"sitekey" xml:"sitekey"`
	// Url，URL
	Url string `json:"url" xml:"url"`
	// Action，Action
	Action string `json:"action,omitempty" xml:"action"`
	// Proxy，Proxy
	Proxy map[string]interface{} `json:"proxy,omitempty" xml:"proxy"`
}
