/*
 * TikHub Private API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tikhub

import (
	"time"
)

// ApiKeyData APIKeyData
type ApiKeyData struct {
	// Api Key Name
	ApiKeyName string `json:"api_key_name" xml:"api_key_name"`
	// Api Key Scopes
	ApiKeyScopes []string `json:"api_key_scopes" xml:"api_key_scopes"`
	// Created At
	CreatedAt time.Time `json:"created_at" xml:"created_at"`
	// Expires At
	ExpiresAt AnyOfDateTimenull `json:"expires_at" xml:"expires_at"`
	// Api Key Status
	ApiKeyStatus int32 `json:"api_key_status" xml:"api_key_status"`
}
