/*
 * TikHub Private API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tikhub

// UserInfoResponseModel UserInfoResponseModel
type UserInfoResponseModel struct {
	// Code，HTTP status code | HTTP状态码
	Code int32 `json:"code,omitempty" xml:"code"`
	// Router，The endpoint that generated this response | 生成此响应的端点
	Router     string     `json:"router,omitempty" xml:"router"`
	ApiKeyData ApiKeyData `json:"api_key_data" xml:"api_key_data"`
	UserData   UserData   `json:"user_data" xml:"user_data"`
}
