/*
 * TikHub Private API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tikhub

// GetHomeFeedRequest GetHomeFeedRequest
type GetHomeFeedRequest struct {
	// Feed Type，推荐类型/Feed type
	FeedType string `json:"feed_type,omitempty" xml:"feed_type"`
	// Need Filter Image，是否只看图文笔记/Whether to view only image notes
	NeedFilterImage bool `json:"need_filter_image,omitempty" xml:"need_filter_image"`
	// Cookie，用户自行提供的已登录的网页Cookie/User provided logged-in web Cookie
	Cookie string `json:"cookie,omitempty" xml:"cookie"`
	// Proxy，代理，格式：http://用户名:密码@IP:端口/Proxy, format: http://username:password@IP:port
	Proxy string `json:"proxy,omitempty" xml:"proxy"`
}
