/*
 * TikHub Private API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tikhub

// ABogusModel ABogusModel
type ABogusModel struct {
	// Url，请求的API URL，需要使用urlencode(url, safe='*')进行编码 | The requested API URL, needs to be encoded using urlencode(url, safe='*')
	Url string `json:"url" xml:"url"`
	// Data，POST请求API时的载荷数据，需要使用urlencode(data, safe='*')进行编码 | The payload data when requesting the API with POST, needs to be encoded using urlencode(data, safe='*')
	Data string `json:"data" xml:"data"`
	// User Agent，请求API时的User-Agent | User-Agent when requesting the API
	UserAgent string `json:"user_agent" xml:"user_agent"`
	// Index 0，加密明文列表的第一个值，无特殊要求，默认为0
	Index0 int32 `json:"index_0,omitempty" xml:"index_0"`
	// Index 1，加密明文列表的第一个值，无特殊要求，默认为1
	Index1 int32 `json:"index_1,omitempty" xml:"index_1"`
	// Index 2，加密明文列表的第一个值，无特殊要求，默认为14
	Index2 int32 `json:"index_2,omitempty" xml:"index_2"`
}
