/*
 * TikHub Private API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tikhub

// BodyTencentCaptchaApiV1CaptchaTencentCaptchaPost Body_tencent_captcha_api_v1_captcha_tencent_captcha_post
type BodyTencentCaptchaApiV1CaptchaTencentCaptchaPost struct {
	// App Id，App ID
	AppId string `json:"app_id" xml:"app_id"`
	// Url，URL
	Url string `json:"url" xml:"url"`
	// Proxy，Proxy
	Proxy map[string]interface{} `json:"proxy,omitempty" xml:"proxy"`
}
