/*
 * TikHub Private API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tikhub

// TikTokAppV3HomeFeed TikTok_APP_V3_Home_Feed
type TikTokAppV3HomeFeed struct {
	// Cookie，用户自己的cookie，可选参数，用于接口返回数据的个性化推荐。/ User's own cookie, optional parameter, used for personalized recommendations of interface return data.
	Cookie string `json:"cookie,omitempty" xml:"cookie"`
}
