/*
 * TikHub Private API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tikhub

// PostCommentRequest PostCommentRequest
type PostCommentRequest struct {
	// AKA Video ID，Video ID, which can be obtained from the sharing link, for example: https://www.tiktok.com/@username/video/7419966340443819295
	AwemeId string `json:"aweme_id,omitempty" xml:"aweme_id"`
	// Comment Content，Comment content, TikTok comment content needs to comply with the specifications, do not contain illegal keywords, otherwise, even if the request is successful, it will be judged as spam comments by the system and will not be displayed.
	Text string `json:"text,omitempty" xml:"text"`
	// User Cookie，User Cookie, you can log in to your TikTok account in the browser and then copy the Cookie information, please use URL-encoded Cookie string when submitting.
	Cookie string `json:"cookie,omitempty" xml:"cookie"`
	// Device ID，Device id, optional, if not filled in, it will be automatically generated, if you need to customize the device id, please use the device information interface to get the device id.
	DeviceId string `json:"device_id,omitempty" xml:"device_id"`
	// Device Install ID，Device install id, optional, if not filled in, it will be automatically generated, if you need to customize the device iid, please use the device information interface to get the device iid.
	Iid string `json:"iid,omitempty" xml:"iid"`
	// Proxy IP，Proxy IP, optional, if not filled in, it will be automatically generated, if you need to customize the proxy IP, please use the proxy IP interface to get the proxy IP.
	Proxy string `json:"proxy,omitempty" xml:"proxy"`
}
